# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efcf8323f823848de2ee3104a2923da13660591b545eb5fdc4b2d4fc415a7d39949d199ec5779405ab935386e498d4c1546a2907f5ce3a9a1dfbf268b7be6ecc

test:
  secret_key_base: 903d6dd3c6d9180ff6eafdfa4ea578c556a3be285ab58d7736b61f4d8a9af8f6e7add53fafe32bce165f217a5342aa9f413c2b46368fc1e3e84a076372332a99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
